name = input("Enter your name:")
matric_no = input("Enter your matric_no:")
level = input("Enter your level:")
age =input("Enter your age:")
department = input("Enter your Department:")
university = input("Enter your University:")
state_of_origin = input("Enter your State_of_origin:")
print("\n===============STUDENT PROFILE===============")
print(f"Name:{name}")
print(f"Matric_no:{matric_no}")
print(f"Level:{level}")
print(f"Age:{age}")
print(f"Department:{name}")
print(f"University:{university}")
print(f"State_of_origin:{state_of_origin}")
print("===============================================")
